import { createFileRoute } from '@tanstack/react-router';

const PAGE = '__site';
const KEYS = ['theme', 'fontBody', 'fontHeading', 'fontBn'];

type Settings = Record<string, string>;

/** Mirrors the saved settings into public/css/site-theme.css so the main
 *  HTML files pick the theme up even before JavaScript runs. */
async function writeThemeCss(settings: Settings) {
  try {
    const fs = await import('node:fs/promises');
    const path = await import('node:path');
    const lines = [
      '/* Generated by the admin settings panel. Do not edit by hand. */',
      ':root{',
      settings['theme'] ? `  --theme-primary:${settings['theme']};` : '',
      settings['theme'] ? `  --bs-primary:${settings['theme']};` : '',
      '}',
    ].filter(Boolean);
    await fs.writeFile(
      path.join(process.cwd(), 'public', 'css', 'site-theme.css'),
      lines.join('\n') + '\n',
      'utf8',
    );
    return true;
  } catch {
    return false;
  }
}

export const Route = createFileRoute('/api/public/cms/settings')({
  server: {
    handlers: {
      GET: async ({ request }) => {
        const { json, isAuthed } = await import('@/lib/cms.server');
        const { cmsDb } = await import('@/lib/cms-db.server');
        const { data, error } = await cmsDb()
          .from('site_content')
          .select('content_key, value')
          .eq('page', PAGE);
        if (error) return json({ settings: {}, error: error.message }, { status: 200 });
        const settings: Settings = {};
        for (const row of data ?? []) settings[row.content_key as string] = row.value as string;
        return json({ settings, authed: isAuthed(request) });
      },
      POST: async ({ request }) => {
        const { json, isAuthed } = await import('@/lib/cms.server');
        if (!isAuthed(request)) return json({ ok: false, error: 'unauthorized' }, { status: 401 });
        const { cmsDb, cmsDbSecrets } = await import('@/lib/cms-db.server');

        let body: { settings?: Settings };
        try {
          body = (await request.json()) as { settings?: Settings };
        } catch {
          return json({ ok: false, error: 'bad request' }, { status: 400 });
        }
        const incoming = body.settings ?? {};
        const rows = KEYS.filter((key) => typeof incoming[key] === 'string').map((key) => ({
          key,
          type: 'text',
          value: String(incoming[key]).slice(0, 300),
        }));
        if (rows.length === 0) return json({ ok: false, error: 'nothing to save' }, { status: 400 });

        const db = cmsDb();
        let lastError = '';
        for (const secret of cmsDbSecrets()) {
          const { error } = await db.rpc('cms_save_content', {
            p_secret: secret,
            p_page: PAGE,
            p_items: rows,
          });
          if (!error) {
            const settings: Settings = {};
            for (const row of rows) settings[row.key] = row.value;
            const css = await writeThemeCss(settings);
            return json({ ok: true, settings, css });
          }
          lastError = error.message;
          if (!/unauthorized/i.test(error.message)) break;
        }
        return json(
          { ok: false, error: `settings save failed: ${lastError || 'unknown error'}` },
          { status: 500 },
        );
      },
    },
  },
});
